import type { NextPage } from "next";
import Head from "next/head";
import Chat from "../components/Chat";
import Sidebar from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <div className="bg-[#a7bcff] min-h-screen flex items-center justify-center">
      <Head>
        <title>WhatsApp 2.0</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="rounded-md overflow-hidden w-4/5 lg:w-3/5 h-[80vh] flex">
        <Sidebar />
        <Chat />
      </main>
    </div>
  );
};

export default Home;
