import type { NextPage } from "next";
import Head from "next/head";
import Chat from "../components/Chat";
import Sidebar from "../components/Sidebar";
import Signin from "../components/Signin";
import { auth, db } from "../firebase";
import Loading from "../components/Loading";
import { useEffect, useState } from "react";
import { doc, setDoc } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);
  const [isLoggedin, setIsLoggedin] = useState(false);

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      setLoading(false);
      if (user) {
        const userData = {
          email: user?.email,
          displayName: user?.displayName,
          photoURL: user?.photoURL,
          uid: user?.uid,
          lastActive: new Date().toString(),
        };

        setDoc(doc(db, "users", user?.uid), userData);

        setIsLoggedin(true);
      } else setIsLoggedin(false);
    });

    return () => {
      unsub();
    };
  }, []);

  if (loading) return <Loading />;
  if (!isLoggedin) return <Signin />;
  return (
    <div className="bg-[#a7bcff] min-h-screen flex items-center justify-center">
      <Head>
        <title>WhatsApp 2.0</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="rounded-md overflow-hidden w-4/5 lg:w-3/5 h-[70vh] sm:h-[80vh] flex">
        <Sidebar />
        <Chat />
      </main>
    </div>
  );
};

export default Home;
